### ISSUE TITLE
ajout amortisseurs moteurs

### ISSUE THREAD

**Issue by liotag** [liotag/impression-3d#10]
Afin de supprimé les bruits aigus, l'ajout de dampers sur les moteurs NEMA17 de ma CR-10 est recommandé (bien qu'apparement controversé) > 
http://www.cr10.fr/ameliorations/

commandés sur aliexpress et reçu ya pas longtemps, je recherche une méthode qui explique bien comment s'y prendre

**Comment by petrachi** [comment]
J'ai commandé & reçu les dampers aussi, je n'ai pas encore installé mais j'ai truvé cette vidéo pour la cr10 : https://www.youtube.com/watch?v=2j9YAcWDoto

J'hésite à installer le damper sur le moteur de l'extruder (axe E), mais X et Y c'est sûr.
Par contre je ne sais pas trop s'il y a besoin de vis en plus ou non ?

**Comment by liotag** [comment]
> 
> 
> J'ai commandé & reçu les dampers aussi, je n'ai pas encore installé mais j'ai truvé cette vidéo pour la cr10 : https://www.youtube.com/watch?v=2j9YAcWDoto
> 
> J'hésite à installer le damper sur le moteur de l'extruder (axe E), mais X et Y c'est sûr.
> Par contre je ne sais pas trop s'il y a besoin de vis en plus ou non ?

touttafay..
sur l'axe X, les vis d'origine sont trop longues, il faut en remplacer 2 par des plus courtes pour pouvoir le monter. la preuve ici : https://youtu.be/2j9YAcWDoto?t=394

**Comment by liotag** [comment]
terminé.
j'ai du meuler les picots au dremel plutôt que fabriquer un adaptateur comme héliox.
il faut donc récupérer deux vis informatiques M3.. mais sinon ça se fait.
j'attends que l'epoxy seche de mon autre bricolage (tube raidisseurs) pour imprimer un truc et vérifier que j'ai pas tout déréglé en installant les dampers :S
