### ISSUE TITLE
Stand Chargeur téléphonne "baleine"

### ISSUE THREAD

**Issue by petrachi** [liotag/impression-3d#11]
Imprimer ce modèle : https://www.thingiverse.com/thing:1100768
Et tester de le polir simplement avec du papier verre.

J'essaierai sans doute une impression en 100 et une en 200 microns pour voir si ça rends le ponçage plus simple.

**Comment by petrachi** [comment]
Alors, 
- J'ai imprimé avec une hauteur variable, donc pas de test pour voir si l'efficacité de ponçage est affecté.
- J'ai imprimé en filament blanc, avec une épaisseur des 'murs' à 0,8. La couleur 'blanche' était assez variable, je pense que la variation est dûe à la trop faible épaisseur des murs qui laissaient entrevoir "l'ombre" de l'infill.
- Le ponçage à bien entamé le plastique par endroit, l'épaisseur des murs à 0,8 était trop faible. La prochaine fois je pense programmer trois ou quatre épaisseurs (au lieu des deux actuelles, j'ai un museau de 0,4)
- J'ai trop rapidement changé pour du papier plus fin, du coup certaines stries des couches d'impression sont encores visibles. Il faut vraiment passer la majorité du temps sur le plus gros grain (j'ai utilisé du 120 pour commencer)
- Pour la finition je suis monté jusqu'à du 1000. La finition était bien, mais on peut encore faire mieux
- à un moment, j'ai poncé trop vite et ça a "arraché' une couche de mur, cette partie là de la piéce était irrattrapable ensuite. Il faut faire attention à changer de zone constament.

En résumé : Imprimer le plus fin possible, faire des murs épais, éliminer toutes les stries avec le plus gros grain, être patient.

**Comment by liotag** [comment]
t'as utilisé quoi comme papier entre le 120 et le 1000?

tu peux réparer avec le mélange maïzena et epoxy, non?
