### ISSUE TITLE
dévidoir filament TUSH

### ISSUE THREAD

**Issue by liotag** [liotag/impression-3d#2]
-
le dévidoir d'origine, sorte de manivelle, de la CR-10 branle un peu
le gros succès sur thingiverse c'est le TUSH (Teh Ultimate Spool Holder) : https://www.thingiverse.com/thing:2047554

bon sauf que sans cales, j'ai un peu peur que ça se casse la gueule, donc voilà le support pour boitier CR-10 que jtrouve malin : https://www.thingiverse.com/thing:2723882

sinon ya ça, plus simple mais faut faire des trous (pistrou) :
https://www.thingiverse.com/thing:3016382

**Comment by liotag** [comment]
imprimé et testé avec succès!
attention fragilité des picots de maintien des roulements.. faut bien les poncer avant d'insérer en force les roulements, sinon ça casse et réimpression obligée (j'en ai cassé 3)

j'ai d'ailleurs trouvé un moyen pour nettoyer des vieux roulements (provenant d'un skate oublié dans un garage). jpeux poster la méthode sur le wiki si besoin.

ah et pour la version avec des trous finalement yaurait pas eu besoin de percer le boitier, car la manivelle d'origine est fixée elle même grace à des trous taraudés, qui peuvent être réutilisés pour fixer ces supports à la place (enfin juste pour un mais jpense c'est mieux d'en laisser un mobile de toute façon, pour pouvoir s'adapter aux différentes dimensions de bobines)

**Comment by petrachi** [comment]
J'ai imprimé ce modéle pour l'alfawise en 100 micron et ça à fonctionné parfaitement avec des roulements 608z, sans ponçage : https://www.thingiverse.com/thing:3152684

**Comment by liotag** [comment]
après test d'impression, ça marche nickel. banco!!
