### ISSUE TITLE
Résine XTC3D pour lisser le PLA

### ISSUE THREAD

**Issue by petrachi** [liotag/impression-3d#7]
Tester l'utilisation de la résine "xtc 3D" pour le finish des impressions en pla

résine sur amazon : https://www.amazon.fr/XTC-3D-Kit-Lissage-impression-3D/dp/B00T3FXO0G/ref=asc_df_B00T3FXO0G/?tag=googshopfr-21&linkCode=df0&hvadid=314004426139&hvpos=1o1&hvnetw=g&hvrand=15912796079508817054&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9055247&hvtargid=pla-575174244426&psc=1&tag=&ref=&adgrpid=61341630206&hvpone=&hvptwo=&hvadid=314004426139&hvpos=1o1&hvnetw=g&hvrand=15912796079508817054&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9055247&hvtargid=pla-575174244426

Vidéos youtube review :
- heliox https://www.youtube.com/watch?v=0oXsnx59KO0
- LFP https://www.youtube.com/watch?v=xwgwfP318SY
- Casque de cosplay https://www.youtube.com/watch?v=h8qvc0wMNYU

**Comment by liotag** [comment]
justement, j'avais lu qu'il ne s'agissait en fait pas d'un lisseur à proprement parler (qui fait fondre pour lisser) mais un mélange bi-composant d'epoxy qui vient par dessus (sorte de croûte lisse quoi)
les gars râlaient sur le fait qu'avec l'effet de mode 'impression 3d', bon nombre d'industriels revendraient des produits déjà commercialisés mais sous l'étiquette 'conçu pour la 3d' histoire de les vendre plus cher.
jvais essayer de retrouver la réf.. mais bonne idée en tout cas!

**Comment by petrachi** [comment]
link to issue #12 & close
